version: '2.3'

services:
  pavlov:
    image: ihadeed/pavlov-server:latest
    volumes:
    - ./Game.ini:/home/steam/pavlovserver/Pavlov/Saved/Config/LinuxServer/Game.ini
    environment:
    - PORT=7500
    ports:
    - 7500:7500/udp
    - 7901:7901/udp
